package org.antlr.zinc.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IStat_Constraints extends BaseConstraintsDescriptor {
  public IStat_Constraints() {
    super(CONCEPTS.IStat$R0);
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept IStat$R0 = MetaAdapterFactory.getInterfaceConcept(0xd84d0ef936eb4841L, 0xbd7c5b126eb1e2b4L, 0x2656959549f38261L, "org.antlr.zinc.structure.IStat");
  }
}
