package org.itemis.mpszinc.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ZAnnotations = 0;
  public static final int ZChunk = 1;
  public static final int ZIdent = 2;
  public static final int ZTiExpr = 3;
  public static final int ZTiExprAndId = 4;
  public static final int ZVarDecl = 5;
  public static final int Zexpr = 6;
  public static final int Zitem = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L);
    builder.put(0x1c2f5a43208c4cdeL, ZAnnotations);
    builder.put(0x409eaa166b5670f7L, ZChunk);
    builder.put(0x1c2f5a43208d3418L, ZIdent);
    builder.put(0x1c2f5a43208d3415L, ZTiExpr);
    builder.put(0x1c2f5a43208c4cdbL, ZTiExprAndId);
    builder.put(0x38e750611a2177e0L, ZVarDecl);
    builder.put(0x1c2f5a43208c4ce4L, Zexpr);
    builder.put(0x38e750611a217188L, Zitem);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
