package org.itemis.mpszinc.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptZAnnotations = createDescriptorForZAnnotations();
  /*package*/ final ConceptDescriptor myConceptZChunk = createDescriptorForZChunk();
  /*package*/ final ConceptDescriptor myConceptZIdent = createDescriptorForZIdent();
  /*package*/ final ConceptDescriptor myConceptZTiExpr = createDescriptorForZTiExpr();
  /*package*/ final ConceptDescriptor myConceptZTiExprAndId = createDescriptorForZTiExprAndId();
  /*package*/ final ConceptDescriptor myConceptZVarDecl = createDescriptorForZVarDecl();
  /*package*/ final ConceptDescriptor myConceptZexpr = createDescriptorForZexpr();
  /*package*/ final ConceptDescriptor myConceptZitem = createDescriptorForZitem();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, "com.mbeddr.core.base");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptZAnnotations, myConceptZChunk, myConceptZIdent, myConceptZTiExpr, myConceptZTiExprAndId, myConceptZVarDecl, myConceptZexpr, myConceptZitem);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ZAnnotations:
        return myConceptZAnnotations;
      case LanguageConceptSwitch.ZChunk:
        return myConceptZChunk;
      case LanguageConceptSwitch.ZIdent:
        return myConceptZIdent;
      case LanguageConceptSwitch.ZTiExpr:
        return myConceptZTiExpr;
      case LanguageConceptSwitch.ZTiExprAndId:
        return myConceptZTiExprAndId;
      case LanguageConceptSwitch.ZVarDecl:
        return myConceptZVarDecl;
      case LanguageConceptSwitch.Zexpr:
        return myConceptZexpr;
      case LanguageConceptSwitch.Zitem:
        return myConceptZitem;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForZAnnotations() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "ZAnnotations", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208c4cdeL);
    b.class_(false, false, false);
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/2030941201322757342");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForZChunk() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "ZChunk", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x409eaa166b5670f7L);
    b.class_(false, false, false);
    b.super_("com.mbeddr.core.base.structure.Chunk", 0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0x6315bcc6effb4ea6L);
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/4656346078014501111");
    b.version(2);
    b.aggregate("item", 0x1c2f5a43208c4ce2L).target(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x38e750611a217188L).optional(true).ordered(true).multiple(true).origin("2030941201322757346").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForZIdent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "ZIdent", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208d3418L);
    b.class_(false, false, false);
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/2030941201322816536");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForZTiExpr() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "ZTiExpr", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208d3415L);
    b.class_(false, false, false);
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/2030941201322816533");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForZTiExprAndId() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "ZTiExprAndId", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208c4cdbL);
    b.class_(false, false, false);
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/2030941201322757339");
    b.version(2);
    b.aggregate("tiExpr", 0x1c2f5a43208d3416L).target(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208d3415L).optional(false).ordered(true).multiple(false).origin("2030941201322816534").done();
    b.aggregate("ident", 0x1c2f5a43208d3419L).target(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208d3418L).optional(false).ordered(true).multiple(false).origin("2030941201322816537").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForZVarDecl() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "ZVarDecl", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x38e750611a2177e0L);
    b.class_(false, false, false);
    b.parent(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x38e750611a217188L);
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/4100334363724576736");
    b.version(2);
    b.aggregate("tiExprId", 0x1c2f5a43208c4cdcL).target(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208c4cdbL).optional(false).ordered(true).multiple(false).origin("2030941201322757340").done();
    b.aggregate("annotations", 0x1c2f5a43208c4cdfL).target(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208c4cdeL).optional(false).ordered(true).multiple(false).origin("2030941201322757343").done();
    b.aggregate("expr", 0x1c2f5a43208c4ce5L).target(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208c4ce4L).optional(true).ordered(true).multiple(false).origin("2030941201322757349").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForZexpr() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "Zexpr", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x1c2f5a43208c4ce4L);
    b.class_(false, false, false);
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/2030941201322757348");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForZitem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.itemis.mpszinc", "Zitem", 0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x38e750611a217188L);
    b.interface_();
    b.origin("r:d13c06ab-2b58-46b6-ac4d-7d26f6b8a141(org.itemis.mpszinc.structure)/4100334363724575112");
    b.version(2);
    b.aggregate("zitem", 0x38e750611a217189L).target(0x90d85b84a6b4322L, 0xaa970a3e74e5cac9L, 0x38e750611a217188L).optional(true).ordered(true).multiple(true).origin("4100334363724575113").done();
    return b.create();
  }
}
